Models/ErrorViewModel.cs
    namespace ASPNET.Models;

    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }

Models/HomeUser.cs
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    namespace TesteEmMvcUser
    {
                    
            public class HomeUser
            {
                public string Usuario { get; set; }
                public string Senha { get; set; }
            }
    }

Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace User.Models
{
    public class UserModel
    {
        public int Id { get; set; }

        public string Nome { get; set; }

        public string Usuario { get; set; }

        public string Senha { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ASPNET.Models;
using TesteEmMvcUser;

namespace ASPNET.Controllers;

public class HomeController : Controller
{

    public IActionResult Index()
    {
        HomeUser usuario = new HomeUser();

        usuario.Usuario = "Kawan";
        usuario.Senha = "Careca";

        return View(usuario);
    }

    public IActionResult Privacy()
    {
        return View();
    }
    

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LogininController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ASPNET.Models;
using TesteEmMvcUser;

namespace ASPNET.Controllers;

public class LogininController : Controller
{

    public IActionResult Loginin()
    {
        return View();
    }

    public IActionResult Create()
    {
        return View();
    }

    public IActionResult Edit()
    {
        return View();
    }

    public IActionResult DeleteWarning()
    {
        return View();
    }

}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Boas Vindas,@Model.Usuario </h1>
    <p>Esse site foi feito no intuito de aprender a mecher em ASP.NET e irá disponibilizar uma criação de usuário </a>.</p>
</div>

Views/Loginin/Create.cshtml
@{
  ViewData["Title"] = "Criar";
}

<div class="text-center">

  <h1 class="display-5">Cadastrar Usuário</h1>


</div>

<form>
  <div class="mb-3">
    <label for="nome" class="form-label">Nome</label>
    <input type="text" class="form-control" placeholder="Digite Seu Primeiro Nome">
  </div>

  <div class="mb-3">
    <label for="user" class="form-label">Usuario</label>
    <input type="text" class="form-control" placeholder="Digite o Usuário desejado">
  </div>

  <div class="mb-3">
    <label for="password" class="form-label">Senha</label>
    <input type="text" class="form-control" placeholder="Digite Sua Senha">
  </div>

  <button type="submit" class="btn btn-primary">Adicionar</button>
  <a class="btn btn-secondary" asp-controller="Loginin" asp-action="Loginin" role="button">Voltar</a>
</form>

Views/Loginin/DeleteWarning.cshtml
@{
    ViewData["Title"] = "DeleteWarning";
}

<div class="text-center">
    <h2>Tem certeza que deseja apagar o Usuario</h2>
    <br>
    <h4>Essa ação é final e não poderá ser revertida</h4>
</div>

<a class="btn btn-primary" asp-controller="Loginin" asp-action="Loginin">Voltar</a>
<a class="btn btn-danger" asp-controller="Loginin" asp-action="Delete">Deletar</a>

Views/Loginin/Edit.cshtml
@{
  ViewData["Title"] = "Edit";
}

<div class="text-center">

  <h1 class="display-5">Editar Usuário</h1>


</div>

<form>
  <div class="mb-3">
    <label for="nome" class="form-label">Nome</label>
    <input type="text" class="form-control" placeholder="Digite Seu Primeiro Nome">
  </div>

  <div class="mb-3">
    <label for="user" class="form-label">Usuario</label>
    <input type="text" class="form-control" placeholder="Digite o Usuário desejado">
  </div>

  <div class="mb-3">
    <label for="password" class="form-label">Senha</label>
    <input type="text" class="form-control" placeholder="Digite Sua Senha">
  </div>

  <button type="submit" class="btn btn-primary">Editar</button>
  <a class="btn btn-secondary" asp-controller="Loginin" asp-action="Loginin" role="button">Voltar</a>
</form>

Views/Loginin/Loginin.cshtml
@{
  ViewData["Title"] = "Loginin";
}

<div class="text-center">

  <div class="d-grid gap-2 d-md-flex justify-content-md-start">
    <a class="btn btn-primary" role="button" asp-controller="Loginin" asp-action="Create">Adicionar Usuario</a>
  </div>
  <br />
  <h1>Listagem de Usuários</h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Usuario</th>
        <th scope="col">Senha</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>Kawan</td>
        <td>admintest</td>
        <td>adminadmin</td>
        <td>
          <div class="btn-group" role="group" aria-label="Basic example">
            <a role="button" class="btn btn-primary" asp-controller="Loginin" asp-action="Edit">Edit</a>
            <a role="button" class="btn btn-danger" asp-controller="Loginin" asp-action="DeleteWarning">Delete</a>
          </div>
        </td>
      </tr>
      <tr>
        <th scope="row">2</th>
        <td>Jacob</td>
        <td>Thornton</td>
        <td>fat</td>
        <td>
          <div class="btn-group" role="group" aria-label="Basic example">
            <a role="button" class="btn btn-primary" asp-controller="Loginin" asp-action="Edit"> Edit</a>
            <a role="button" class="btn btn-danger" asp-controller="Loginin" asp-action="DeleteWarning">Delete</a>
          </div>
        </td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>David</td>
        <td>Davethedogontherave</td>
        <td>Dance</td>
        <td>
          <div class="btn-group" role="group" aria-label="Basic example">
            <a role="button" class="btn btn-primary" asp-controller="Loginin" asp-action="Edit">Edit</a>
            <a role="button" class="btn btn-danger" asp-controller="Loginin" asp-action="DeleteWarning">Delete</a>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TesteASPNET</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPNET.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TesteASPNET</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Extras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loginin" asp-action="Loginin">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Projeto feito por Kawan Miranda - <a asp-area="" asp-controller="Home" asp-action="Privacy">Extras</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>